backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://artbyskylee.com

collections:
  - name: "gallery"
    label: "Gallery"
    format: "json"
    extension: "json"
    file: "src/site/_data/gallery.json"
      fields:
        - {label: Layout, name: "layout", widget: "hidden", default: "layouts/base.html"}
        - {label: Title, name: page_title, widget: string}
        - label: "Featured Works"
          name: "featuredWorks"
          widget: "list"
          summary: '{{fields.title}}'
          label_singular: "Work"
          fields: 
            - {label: Image, name: image, widget: image}
            - {label: Title, name: title, widget: string, required: false}
            - {label: Description, name: description, widget: text, required: false}

# These lines should *not* be indented
media_folder: "src/site/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/site/img" # The src attribute for uploaded media will begin with /images/uploads