backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name : "posts" # routes in cms
    label: "Blog Posts" # label in UI 
    folder: "posts" # place this lives in in 11ty or SSG
    create: true
    slug:  "{{year}}-{{month}}-{{day}}-{{slug}}" # final output url on client
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.html"} #name is variable in template
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/site/index.html"
        fields:
          - {label: Layout, name: "layout", widget: "hidden", default: "layouts/base.html"}
          - {label: Title, name: page_title, widget: string}

# These lines should *not* be indented
media_folder: "src/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img" # The src attribute for uploaded media will begin with /images/uploads